<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up(): void {
Schema::create('companies',function(Blueprint $t){$t->id();$t->uuid('uuid');$t->string('name');$t->string('slug')->unique();$t->string('email');$t->string('phone')->nullable();$t->string('address')->nullable();$t->string('city')->nullable();$t->string('postal_code')->nullable();$t->string('country')->default('France');$t->string('siret')->nullable();$t->string('tva_number')->nullable();$t->string('logo')->nullable();$t->string('subscription_plan')->default('trial');$t->string('subscription_status')->default('trialing');$t->timestamp('trial_ends_at')->nullable();$t->timestamps();});
Schema::create('users',function(Blueprint $t){$t->id();$t->uuid('uuid')->nullable();$t->foreignId('company_id')->nullable()->constrained()->nullOnDelete();$t->string('name');$t->string('email')->unique();$t->timestamp('email_verified_at')->nullable();$t->string('password');$t->string('role')->default('admin');$t->string('phone')->nullable();$t->string('avatar')->nullable();$t->rememberToken();$t->timestamps();});
foreach(['categories','suppliers','customers','products','quotes','quote_items','invoices','invoice_items','stock_movements','payments','activity_logs'] as $x){}
Schema::create('categories',fn(Blueprint $t)=>[$t->id(),$t->foreignId('company_id')->constrained()->cascadeOnDelete(),$t->string('name'),$t->string('slug'),$t->timestamps()]);
Schema::create('products',function(Blueprint $t){$t->id();$t->uuid('uuid');$t->foreignId('company_id')->constrained()->cascadeOnDelete();$t->foreignId('category_id')->nullable()->constrained()->nullOnDelete();$t->string('name');$t->string('reference');$t->string('barcode')->nullable();$t->string('brand')->nullable();$t->text('description')->nullable();$t->decimal('purchase_price',10,2);$t->decimal('selling_price',10,2);$t->integer('quantity')->default(0);$t->integer('min_stock_alert')->default(0);$t->string('image')->nullable();$t->string('status')->default('active');$t->timestamps();});
Schema::create('customers',function(Blueprint $t){$t->id();$t->uuid('uuid');$t->foreignId('company_id')->constrained()->cascadeOnDelete();$t->string('first_name');$t->string('last_name');$t->string('phone');$t->string('email')->nullable();$t->string('address')->nullable();$t->string('city')->nullable();$t->string('postal_code')->nullable();$t->string('vehicle_brand')->nullable();$t->string('vehicle_model')->nullable();$t->string('license_plate')->nullable();$t->text('notes')->nullable();$t->timestamps();});
Schema::create('suppliers',function(Blueprint $t){$t->id();$t->uuid('uuid');$t->foreignId('company_id')->constrained()->cascadeOnDelete();$t->string('name');$t->string('email')->nullable();$t->string('phone')->nullable();$t->string('address')->nullable();$t->string('city')->nullable();$t->text('notes')->nullable();$t->timestamps();});
Schema::create('quotes',function(Blueprint $t){$t->id();$t->uuid('uuid');$t->foreignId('company_id')->constrained()->cascadeOnDelete();$t->foreignId('customer_id')->nullable()->constrained()->nullOnDelete();$t->string('quote_number');$t->string('status')->default('draft');$t->decimal('subtotal',10,2)->default(0);$t->decimal('tax_total',10,2)->default(0);$t->decimal('discount_total',10,2)->default(0);$t->decimal('total',10,2)->default(0);$t->date('valid_until')->nullable();$t->text('notes')->nullable();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
Schema::create('quote_items',function(Blueprint $t){$t->id();$t->foreignId('quote_id')->constrained()->cascadeOnDelete();$t->foreignId('product_id')->nullable()->constrained()->nullOnDelete();$t->string('description');$t->decimal('quantity',10,2);$t->decimal('unit_price',10,2);$t->decimal('tax_rate',5,2)->default(20);$t->decimal('total',10,2);$t->timestamps();});
Schema::create('invoices',function(Blueprint $t){$t->id();$t->uuid('uuid');$t->foreignId('company_id')->constrained()->cascadeOnDelete();$t->foreignId('customer_id')->nullable()->constrained()->nullOnDelete();$t->string('invoice_number');$t->string('status')->default('draft');$t->string('payment_status')->default('unpaid');$t->decimal('subtotal',10,2)->default(0);$t->decimal('tax_total',10,2)->default(0);$t->decimal('discount_total',10,2)->default(0);$t->decimal('total',10,2)->default(0);$t->date('due_date')->nullable();$t->timestamp('paid_at')->nullable();$t->text('notes')->nullable();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
Schema::create('invoice_items',function(Blueprint $t){$t->id();$t->foreignId('invoice_id')->constrained()->cascadeOnDelete();$t->foreignId('product_id')->nullable()->constrained()->nullOnDelete();$t->string('description');$t->decimal('quantity',10,2);$t->decimal('unit_price',10,2);$t->decimal('tax_rate',5,2)->default(20);$t->decimal('total',10,2);$t->timestamps();});
Schema::create('stock_movements',function(Blueprint $t){$t->id();$t->uuid('uuid');$t->foreignId('company_id')->constrained()->cascadeOnDelete();$t->foreignId('product_id')->constrained()->cascadeOnDelete();$t->string('type');$t->integer('quantity');$t->integer('before_quantity');$t->integer('after_quantity');$t->text('notes')->nullable();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
Schema::create('payments',function(Blueprint $t){$t->id();$t->uuid('uuid');$t->foreignId('company_id')->constrained()->cascadeOnDelete();$t->foreignId('invoice_id')->constrained()->cascadeOnDelete();$t->decimal('amount',10,2);$t->string('payment_method');$t->date('payment_date');$t->string('reference')->nullable();$t->text('notes')->nullable();$t->timestamps();});
Schema::create('activity_logs',function(Blueprint $t){$t->id();$t->foreignId('company_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->string('action');$t->string('model_type')->nullable();$t->unsignedBigInteger('model_id')->nullable();$t->text('description')->nullable();$t->string('ip_address')->nullable();$t->timestamps();});
} public function down(): void {} };
