<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
public function up(): void {
Schema::create('categories', function (Blueprint $table): void {$table->id();$table->foreignId('company_id')->constrained()->cascadeOnDelete();$table->uuid('uuid')->unique();$table->string('name');$table->timestamps();});
Schema::create('suppliers', function (Blueprint $table): void {$table->id();$table->foreignId('company_id')->constrained()->cascadeOnDelete();$table->uuid('uuid')->unique();$table->string('name');$table->string('email')->nullable();$table->string('phone')->nullable();$table->string('address')->nullable();$table->timestamps();});
Schema::create('customers', function (Blueprint $table): void {$table->id();$table->foreignId('company_id')->constrained()->cascadeOnDelete();$table->uuid('uuid')->unique();$table->string('first_name');$table->string('last_name');$table->string('phone')->nullable();$table->string('email')->nullable();$table->string('address')->nullable();$table->string('city')->nullable();$table->string('postal_code',20)->nullable();$table->string('vehicle_brand')->nullable();$table->string('vehicle_model')->nullable();$table->string('license_plate')->nullable();$table->text('notes')->nullable();$table->timestamps();});
Schema::create('products', function (Blueprint $table): void {$table->id();$table->foreignId('company_id')->constrained()->cascadeOnDelete();$table->foreignId('category_id')->nullable()->constrained()->nullOnDelete();$table->uuid('uuid')->unique();$table->string('name');$table->string('reference')->index();$table->string('barcode')->nullable();$table->string('brand')->nullable();$table->text('description')->nullable();$table->decimal('purchase_price',10,2)->default(0);$table->decimal('selling_price',10,2)->default(0);$table->integer('quantity')->default(0);$table->integer('min_stock_alert')->default(0);$table->string('image')->nullable();$table->boolean('status')->default(true);$table->timestamps();});
Schema::create('quotes', function (Blueprint $table): void {$table->id();$table->foreignId('company_id')->constrained()->cascadeOnDelete();$table->foreignId('customer_id')->constrained()->cascadeOnDelete();$table->uuid('uuid')->unique();$table->string('quote_number')->index();$table->string('status')->default('draft');$table->decimal('subtotal',10,2)->default(0);$table->decimal('tax_total',10,2)->default(0);$table->decimal('discount_total',10,2)->default(0);$table->decimal('total',10,2)->default(0);$table->date('valid_until')->nullable();$table->text('notes')->nullable();$table->foreignId('created_by')->constrained('users');$table->timestamps();});
Schema::create('quote_items', function (Blueprint $table): void {$table->id();$table->foreignId('company_id')->constrained()->cascadeOnDelete();$table->foreignId('quote_id')->constrained()->cascadeOnDelete();$table->foreignId('product_id')->nullable()->constrained()->nullOnDelete();$table->string('description');$table->decimal('quantity',10,2);$table->decimal('unit_price',10,2);$table->decimal('tax_rate',5,2)->default(20);$table->decimal('total',10,2);$table->timestamps();});
Schema::create('invoices', function (Blueprint $table): void {$table->id();$table->foreignId('company_id')->constrained()->cascadeOnDelete();$table->foreignId('customer_id')->constrained()->cascadeOnDelete();$table->uuid('uuid')->unique();$table->string('invoice_number')->index();$table->string('status')->default('draft');$table->string('payment_status')->default('pending');$table->decimal('subtotal',10,2)->default(0);$table->decimal('tax_total',10,2)->default(0);$table->decimal('discount_total',10,2)->default(0);$table->decimal('total',10,2)->default(0);$table->date('due_date')->nullable();$table->timestamp('paid_at')->nullable();$table->text('notes')->nullable();$table->foreignId('created_by')->constrained('users');$table->timestamps();});
Schema::create('invoice_items', function (Blueprint $table): void {$table->id();$table->foreignId('company_id')->constrained()->cascadeOnDelete();$table->foreignId('invoice_id')->constrained()->cascadeOnDelete();$table->foreignId('product_id')->nullable()->constrained()->nullOnDelete();$table->string('description');$table->decimal('quantity',10,2);$table->decimal('unit_price',10,2);$table->decimal('tax_rate',5,2)->default(20);$table->decimal('total',10,2);$table->timestamps();});
Schema::create('stock_movements', function (Blueprint $table): void {$table->id();$table->foreignId('company_id')->constrained()->cascadeOnDelete();$table->foreignId('product_id')->constrained()->cascadeOnDelete();$table->string('type');$table->integer('quantity');$table->string('reference')->nullable();$table->text('notes')->nullable();$table->foreignId('created_by')->constrained('users');$table->timestamps();});
Schema::create('payments', function (Blueprint $table): void {$table->id();$table->foreignId('company_id')->constrained()->cascadeOnDelete();$table->foreignId('invoice_id')->constrained()->cascadeOnDelete();$table->decimal('amount',10,2);$table->string('method');$table->string('status')->default('pending');$table->timestamp('paid_at')->nullable();$table->timestamps();});
Schema::create('activity_logs', function (Blueprint $table): void {$table->id();$table->foreignId('company_id')->constrained()->cascadeOnDelete();$table->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$table->string('action');$table->string('subject_type')->nullable();$table->unsignedBigInteger('subject_id')->nullable();$table->json('properties')->nullable();$table->timestamps();});
}
public function down(): void {foreach(['activity_logs','payments','stock_movements','invoice_items','invoices','quote_items','quotes','products','customers','suppliers','categories'] as $table){Schema::dropIfExists($table);} }
};
